version: '3.7'
services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:5001
    networks:
      - processor-net
  minio:
    container_name: minio'
    image: minio/minio:RELEASE.2021-07-12T02-44-53Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:	
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    
networks:
  processor-net:
    driver: bridge